### ISSUE TITLE
Please Read This

### ISSUE THREAD

**Issue by zjhzxhz** [ShuyangLiu/GoingOn#1]
There're several things need to attention:

1. I  updated the structure of database, please recreate the database in your PC
2. I set the password of root to `` (empty), because it's more convenient to deploy this application to another PC.

Thanks.

**Comment by zjhzxhz** [comment]
BTW, before you run the application, please execute following command in the Terminal

```
npm install
```

**Comment by zjhzxhz** [comment]
There're several things for you to do:

In the file `views/accounts/signup.html`, from line 150 to line 184, please fill in the error message.
For example, for the line 151, you may do as following:

```
errorMessage += 'You cannot leave username field empty.<br>';
```

Another thing is please fill in the organization types in the file `views/accounts/signup.html`, from line 67 to line 68.
For example:

```
<select id="organzation-type" name="organzation-type">
    <option value="Art">Art</option>
</select>
```
And in the file `controllers/accounts.js`, at the line 153. Please also fill in the organization types as following:

```
var organizationTypeOptions = ['Art', 'Another Type'];
```

The value in this file MUST be the same as the one in HTML.

If you have any questions, please ask me for free.
@ShuyangLiu @GeyangYu

**Comment by ShuyangLiu** [comment]
Thanks so much!
