### ISSUE TITLE
Milestone 3 Questions

### ISSUE THREAD

**Issue by ShuyangLiu** [ShuyangLiu/GoingOn#2]
Hello!

I am trying to use cookie to identify if the user is logged in or not. I used 
```
if(rememberMe) {
    var minute = 60 * 100000;
    response.cookie('remember', 1, { maxAge: minute });
}
```
in acount.js and it sends a cookie when the user logged in. However, when I try to get the cookie from request in the GET function in index.js using `request.cookies`, it seems it is skipping the code without checking if there is any cookie (since I put `console.log` there but nothing is shown on the console, neither "find a cookie" nor "not find a cookie" ). 

Anyone has any idea? 
@zjhzxhz 
@GeyangYu 
Thanks

**Comment by zjhzxhz** [comment]
I think you should use `session` instead of `cookie`.

You can look at this [documentation](https://codeforgeek.com/2014/09/manage-session-using-node-js-express-4/) to learn how to use it.

**Comment by ShuyangLiu** [comment]
Hello! 
Sorry for bothering you again. 
I used the same code as the tutorial said but it seems there still are some problems. One thing that I am really concerned with is that it never get into the function of `router.get('/')` in `index.js` since I put some `console.log` there but none shows up. I think one of the possible mistakes I made is putting the wrong path/url 's since there seems to be `accounts/` before all of the url's in `accounts.js`. However, if I put `accounts/profile` for `forwardUrl` in `signin.html`, it always appears to be `accounts/accounts/profile` as a result. So what url's should I put for the functions in `accounts.js` and `index.js`? Also, how come it never enter the `router.get('/')` function? 
@zjhzxhz 
Thanks!

**Comment by ShuyangLiu** [comment]
It seems the problem can be fixed by changing the url for home page to `/home`. Now using `localhost:3000/home` as root directory, the session can be checked and redirect to the profile page if logged in

**Comment by zjhzxhz** [comment]
Sorry, I don't now how to enter the `router.get('/')` function either. :(

**Comment by ShuyangLiu** [comment]
I guess it's because Express redirect to `index.html` automatically since the view path of it is set to default. Therefore it was not the `router.get('/')` that rendered the home page but the default path (sort of...?). Anyway, I think it is ok for now to manually add `/home` when trying to access the page

**Comment by zjhzxhz** [comment]
Here's an alternative solution. Please `pull` the code.
Maybe it's not perfect, but it works.

Another thing to say is that PLEASE WRITE ROUTE IN `controllers/*.js` instead of `app.js`.

**Comment by ShuyangLiu** [comment]
Yeah that works too. Thanks! I wonder what's the difference between `app.get` and `router.get`?

**Comment by zjhzxhz** [comment]
In `app.js`, `app` is a variable declared in line 10.
In `controllers/*.js`, `router` is a variable declared in line 2.

I think  they're the same in the lower layer. But according to the documentation of Express.js, you should use it like this.

**Comment by ShuyangLiu** [comment]
Hello!

Just got another question: is there any special meaning for `.action` (as in `signIn.action` and `signUp.action`)? I tried to use the same thing for updating user information but always get a `page not found`. So now I am using a POST request to this url: `/accounts/update`. It can update information in the database but always gives a JSON response in return. So I wonder, is there any special JSON parsing procedures in `.action`? If so, where exactly is it? 

Thanks,
@zjhzxhz

**Comment by zjhzxhz** [comment]
(余戈杨同学说两个中国人用什么英文)

.action没有特殊的含义, 只是一个习惯而已.
如果一直Page Not Found可能是你router没有写对吧 . 写完之后需要重启application.

BTW,  it's time to sleep. 熬夜伤身体 :)

**Comment by ShuyangLiu** [comment]
（哈哈只是觉得在github上说英语显得比较专业...)

我现在在POST 的里面用`/update`当我的url 其他我都没有改， 然后它可以修改信息但是不知为何转不到我指定的下一个页面而是在浏览器里给我result的json形式，console那边也没有显示什么错误，所以我以为你写了其他的东西用来parse json？ 没关系我再看看我写的router！多谢！（不过有可能还会问你一些问题...)

**Comment by zjhzxhz** [comment]
你在Line 139和Line 154有两个相同的URL, 都叫做update, 虽然请求方式不一样.
所以你现在的问题是每次访问update都会请求到Line 154的那个function吗?

JSON本来就是JavaScript对象呀, 不需要解析.

**Comment by ShuyangLiu** [comment]
访问update不会到Line 154， 只有在提交update信息的时候才会，但是不知道为什么，虽然可以更新数据库里面的信息，但是到不了ajax那边的success然后转到下一个页面， 而是给我在浏览器里显示result的json形式， 我用update.action试了一下但还是page not found 虽然几乎都是照着signUp.action写的？

**Comment by zjhzxhz** [comment]
有一坨语法错误你没有看到吗? Console里都告诉你Error的位置了.
艾玛~ 图片上传不上来~

已经Fix了, 具体的Change Log请参见[此处](https://github.com/ShuyangLiu/GoingOn/commit/4eac1d9b425b3aaffb0a5771eb147e8ed3889f6a).

**Comment by zjhzxhz** [comment]
还有你这个业务需求有问题. 我觉得用户不应该允许修改用户名.

**Comment by ShuyangLiu** [comment]
诶？？我的console没有给我任何信息啊？？？原来是`,`和`;`的问题...我想的是用户可以改用户名但是不能改变email信息

**Comment by zjhzxhz** [comment]
你在用什么浏览器? 
我用的是Chrome.

**Comment by ShuyangLiu** [comment]
我的也是啊？？？

**Comment by zjhzxhz** [comment]
呃…… 那应该有会有提示的呀!

On Sun, Nov 22, 2015 at 12:11 PM, Shuyang Liu <notifications@github.com>
wrote:

> 我的也是啊？？？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShuyangLiu/GoingOn/issues/2#issuecomment-158706863>.
>



-- 

谢浩哲

**Comment by ShuyangLiu** [comment]
然而什么都没有啊？？？当时只是说page not found，然而console上什么都没有啊？？？不过现在好了！这回真的多谢了！下回我会把我的
sublime字号再调大的

**Comment by ShuyangLiu** [comment]
Subject Line (for proofing, doesn't show in actual email)
<https://www.digitalocean.com>                         == Deploy a Server
For Free! ==

  Your friend sliu44 has been using DigitalOcean – a cloud hosting
service designed just for developers – and thought you might want to give
it a shot. You can deploy a server in 55 seconds from our control panel or
use our simple API. 

 Because you’ve been invited by a friend, we’d like to give you a $10
credit to try it out. Just use this link to create an account and you’ll
be credited automatically.

 Redeem Your Credit
<https://cloud.digitalocean.com/accept?code=cb55a0cd95ebe1&amp;utm_campaign=Referral_Invite&amp;utm_medium=Referral_Program&amp;utm_source=Mandrill>

  Happy Coding,
 DigitalOcean 

            © DigitalOcean <http://do.co/email_twitter>
<http://do.co/email_gplus> <http://do.co/email_facebook>
